### ISSUE TITLE
Using custom rules with gulp-tslint

### ISSUE THREAD

**Issue by lumaxis** [panuhorsmalahti/gulp-tslint#103]
I'm currently looking into adding bunch of custom rules to our project or maybe using some existing third-party rules like https://github.com/Microsoft/tslint-microsoft-contrib .

Is this already possible? I haven't found a way to use the `rulesDirectory` option through `gulp-tslint`, am I missing something?
Thanks a bunch!

**Comment by panuhorsmalahti** [comment]
Yes, it's possible: https://github.com/panuhorsmalahti/gulp-tslint/blob/master/test/gulpfile.js#L369

**Comment by lumaxis** [comment]
Perfect, thank you!
