### ISSUE TITLE
Question: is there any way to see the duration of individual rules?

### ISSUE THREAD

**Issue by negberts** [panuhorsmalahti/gulp-tslint#115]
Thanks for wanting to report an issue you've found in gulp-tslint. Please make sure it's an issue in gulp-tslint, not tslint. Otherwise please submit an issue to tslint: https://github.com/palantir/tslint/issues/new. Please delete this text and fill in the template below.

gulp-tslint version: 7.1.0 
tslint version: 4.5.1
Operating system: Windows 10

TSLint is during pretty long since we are using rules from codelyzer and rules from tslint-contrib-microsoft. I wanna know which rules are 'expensive'. Is there any way in the report system to maybe log the duration of each individual rule executed?

**Comment by panuhorsmalahti** [comment]
This is a tslint issue, please file an issue at https://github.com/palantir/tslint/issues/new
