### ISSUE TITLE
Support for tslint v5 rule severity

### ISSUE THREAD

**Issue by KurtPreston** [panuhorsmalahti/gulp-tslint#116]
tslint 5.0 introduced the notion of rule severity, allowing rules to either have an `error` or a `warning` severity.

`error`-level rules are reported to the console and cause tslint to output an exit code of `1`.
`warning`-level rules are reported to the console, but output the success exit code of `0`.

Currently, `gulp-tslint` will output an error code even when `tslint` only reports warnings.

**Comment by sjbarag** [comment]
@KurtPreston - this is fixed in `gulp-tslint@8.1` with the addition of the `allowWarnings` options to the `report` function.  Let me know if it doesn't work out for you! 😄
