### ISSUE TITLE
@types should be in devDependencies

### ISSUE THREAD

**Issue by jbedard** [panuhorsmalahti/gulp-tslint#126]
Since 8.1 some [type definitions](https://github.com/panuhorsmalahti/gulp-tslint/blob/6042908c7c01433c24571228c4cc520b8f664440/package.json#L30-L32) were added to `dependencies`. I think these should be in the `devDependencies` so they don't get installed along with gulp-tslint?

**Comment by panuhorsmalahti** [comment]
Fixed in 8.1.1.

**Comment by demurgos** [comment]
Types with global definitions (environment/globals) should be installed by the consumer, but all the other types should be regular dependencies so type definitions work reliably.
In practice, it means that types for normal dependencies should also be normal dependencies.
