### ISSUE TITLE
No `Linter` defined on tslint object

### ISSUE THREAD

**Issue by BurtHarris** [panuhorsmalahti/gulp-tslint#132]
Following code in the README, I'm trying to call `tslint.Linter.createProgrm()`, but it fails because `Linter` isn't defined

gulp-tslint version: 8.1.1
tslint version: 5.5.0
Operating system: Windows 10.0.15063

Example gulp configuration (if applicable):
  ```
  const gulp = require('gulp')
  const sourcemaps = require('gulp-sourcemaps')
  const ts = require('gulp-typescript')

  const tslint = require('gulp-tslint')
  const tsProject = ts.createProject('tsconfig.json')
  const typescriptTasks = ['tslint', 'compile']


  gulp.task('tslint', ()=> {
    const program = tslint.Linter.createProgram("./tsconfig.json");
    return tsProject.src()
      .pipe(gulpTslint({ program }))
  })

  gulp.task('compile', () => {
    return tsProject.src()
      .pipe(sourcemaps.init())
      .pipe(tsProject(ts.reporter.defaultReporter()))
      .pipe(sourcemaps.write())
      .pipe(gulp.dest(tsProject.config.compilerOptions.outDir))
  })

  gulp.task('watch', typescriptTasks, () => {
    gulp.watch(['src/**/*.ts'],  typescriptTasks)
  })

  gulp.task('default', typescriptTasks)
  ```
Error console output:

  [15:43:15] Using gulpfile C:\code\tsdoc\gulpfile.js
  [15:43:15] Starting 'tslint'...
  [15:43:15] 'tslint' errored after 110 μs
  [15:43:15] TypeError: Cannot read property 'createProgram' of undefined
    at Gulp.gulp.task (C:\code\tsdoc\gulpfile.js:11:34)
    at module.exports (C:\code\tsdoc\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\code\tsdoc\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\code\tsdoc\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\code\tsdoc\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Burt_\AppData\Roaming\nvm\v8.1.3\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:51:20
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)

**Comment by tamj0rd2** [comment]
You need to use the Linter from `tslint`, not `gulp-tslint`

So what you want is this
```typescript
const gulp = require('gulp')
const sourcemaps = require('gulp-sourcemaps')
const ts = require('gulp-typescript')

const tslint = require('gulp-tslint')
const gulpTslint = require('gulp-tslint')
const tsProject = ts.createProject('tsconfig.json')
const typescriptTasks = ['tslint', 'compile']


gulp.task('tslint', ()=> {
  const program = tslint.Linter.createProgram("./tsconfig.json");
  return tsProject.src()
    .pipe(gulpTslint({ program }))
})

gulp.task('compile', () => {
  return tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(tsProject(ts.reporter.defaultReporter()))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(tsProject.config.compilerOptions.outDir))
})

gulp.task('watch', typescriptTasks, () => {
  gulp.watch(['src/**/*.ts'],  typescriptTasks)
})

gulp.task('default', typescriptTasks)
```

**Comment by BurtHarris** [comment]
Thanks @tamj0rd2, @panuhorsmalahti.   

I'd like to suggest that the README could be improved to be less confusing around this.   In the first usage example, it makes `tslint = require('gulp-tslint')` .   But in later examples it assigns while `tslint = require('tslint')`.   It would be an improvement to consistently use `const gulpTslint = require('gulp-tslint')` throughout the readme, as in the example above.
