### ISSUE TITLE
Gulp examples do not correctly return the stream

### ISSUE THREAD

**Issue by gwicksted** [panuhorsmalahti/gulp-tslint#138]
gulp-tslint version: (latest source #53534f8) 8.1.2
tslint version: 5.8.0
gulp: 3.9.1
node: 9.0.0
Operating system: Windows 10 x64

Example gulp configuration -- here are just 2 examples from the readme: 

```js
gulp.task("tslint", () =>
    gulp.src("source.ts")
        .pipe(tslint({
            formatter: "verbose"
        }))
        .pipe(tslint.report())
);

gulp.task("invalid-noemit", () =>
    gulp.src("input.ts")
        .pipe(tslint({
            formatter: "prose"
        }))
        .pipe(tslint.report({
            emitError: false
        }))
);
```

Corrected documentation (just the `return` statement added):

```js
gulp.task("tslint", () =>
    return gulp.src("source.ts")
        .pipe(tslint({
            formatter: "verbose"
        }))
        .pipe(tslint.report())
);

gulp.task("invalid-noemit", () =>
    return gulp.src("input.ts")
        .pipe(tslint({
            formatter: "prose"
        }))
        .pipe(tslint.report({
            emitError: false
        }))
);
```

Error console output:
```
[12:40:13] Using gulpfile
[12:40:13] Starting 'lint'...
[12:40:14] Finished 'lint' after
```
*long pause here*

Reasoning behind the change:

If you don't return the `stream`, gulp expects the callback to be called so it ends up waiting unnecessarily after tslint completes.

**Comment by panuhorsmalahti** [comment]
`() => gulp.src("input.ts")` is a ES6 short-hand for `() => { return gulp.src("input.ts")`. Your examples are not syntactically correct.

**Comment by gwicksted** [comment]
Can't believe I missed that!  My test had the `{}`.  Sorry!  My bad.
