### ISSUE TITLE
gulp-tslint ignores the no-irregular-whitespace rule

### ISSUE THREAD

**Issue by FiniteLooper** [panuhorsmalahti/gulp-tslint#139]
gulp-tslint version: `8.1.2`
tslint version: `5.8.0`
Operating system: Windows 10

I have a TS file that has "irregular whitespace" reported via the [`no-irregular-whitespace` tslint rule](https://palantir.github.io/tslint/rules/no-irregular-whitespace).  I can verify this by running tslint from the command line:
```
tslint --format stylish --config tslint.json app/**/*.ts
```
which produces this console output
```
app/App.module.ts
ERROR: 1:1  no-irregular-whitespace  Irregular whitespace not allowed
```

However from the exact same project I have gulp-tslint set up like this:

```ts
const gulp        = require("gulp");
const plumber     = require("gulp-plumber");
const gulpTslint  = require("gulp-tslint");
const tslint      = require("tslint");

gulp.task("lint", () => {
    return gulp.src(["app/**/*.ts"])
        .pipe(plumber())
        .pipe(gulpTslint({
            formatter: "stylish",
        }))
        .pipe(gulpTslint.report());
});
```

and calling `gulp lint` produces zero errors!  This wa first discovered in https://github.com/vladeck/TSLint/issues/8 where I thought it was an issue that that project, but I was wrong.

I've attached a small demo project: **[📂 irregular-whitespace-test.zip](https://github.com/panuhorsmalahti/gulp-tslint/files/1441120/irregular-whitespace-test.zip)**

download it and run `npm install`, then run `gulp lint` and `npm run lint` to see the different outputs.

![no-irregular-whitespace](https://user-images.githubusercontent.com/463685/32375106-c788aa3a-c076-11e7-9823-cf56b53b9955.png)

**Comment by panuhorsmalahti** [comment]
Can you verify that the tslint.json you've created is used by gulp-tslint? I haven't debugged this yet, but it's possible that it's not using the tslint.json file in your project folder for some reason, and maybe falls back to the default lint rules - which might not include the no-irregular-whitespace rule.

You could test by e.g. using "tslint.json can be supplied as a parameter by setting the configuration property" as per the readme.

**Comment by chrismbarr** [comment]
Yes, I have verified it.  To be sure though, here's a slightly modified version of the same project that only enables **only** `no-irregular-whitespace` and `no-var-keyword`.  I have used the `var` keyword in the TS file once.

Running tslint via command line produces 2 errors as expected, and running via gulp-tslint only produces 1 error, skipping the `no-irregular-whitespace` rule.  Download the below attachment to see.

### [📂 no-irregular-whitespace-2.zip](https://github.com/panuhorsmalahti/gulp-tslint/files/1441903/no-irregular-whitespace-2.zip)

**Comment by chrismbarr** [comment]
@panuhorsmalahti any updates or feedback about this?  

I have a feeling it's probably related to [this line](https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.ts#L161) in the source of `gulp-tslint`.
```ts
tslint.lint(file.path, file.contents.toString("utf8"), configuration);
```

If this auto-converts things to UTF-8 before linting, then (I think...) it will never be able to detect [the unicode characters that the `no-irregular-whitespace` rule is looking for](https://github.com/palantir/tslint/blob/master/src/rules/noIrregularWhitespaceRule.ts#L45).
