### ISSUE TITLE
Drop dependency on deprecated `gulp-util`

### ISSUE THREAD

**Issue by demurgos** [panuhorsmalahti/gulp-tslint#140]
Hi,
[`gulp-util`](https://github.com/gulpjs/gulp-util) is deprecated. It should be replaced by dependencies on the individual components used by `gulp-eslint`. The README lists alternatives for the different components.

See https://github.com/gulpjs/gulp/issues/2065

**Comment by panuhorsmalahti** [comment]
Should be straightforward to replace:
* gutil.colors => https://www.npmjs.com/package/ansi-colors
* gutil.PluginError => https://www.npmjs.com/package/plugin-error
* gutil.log => https://www.npmjs.com/package/fancy-log

**Comment by demurgos** [comment]
Hi,
I confirm that this is straightforward replacement.
The main blocker is the lack of type definitions for `plugin-error`. I opened a [PR](https://github.com/gulpjs/plugin-error/pull/6) to fix this.
I have a patched version of `gulp-tslint` ready to be submitted but it uses my temporary fork of `plugin-error` until the types are available. I'll submit it is as soon as the types are ready.

**Comment by demurgos** [comment]
The types for `plugin-error` got merged, they should be published soon.

**Comment by demurgos** [comment]
`plugin-error@1.0.0` has been published, it bundles its types.

**Comment by Silic0nS0ldier** [comment]
`ansi-colors` being suggested is likely down to Gulp using it. If features unique to `chalk` aren't being used, may as well use `ansi-colors`. `@types/ansi-colors` has got the library covered by the way. I'll see if I can get typings in it directly too since I'm probably going to be using it in my own projects.

**Comment by demurgos** [comment]
@Silic0nS0ldier Feel free to open a new PR. Having a smaller dependency would be a good thing.

I'm closing this issue since the updated version is now on _npm_.
