### ISSUE TITLE
failed uploading my shiny app on shinyserver.io

### ISSUE THREAD

**Issue by nmbaya** [panuhorsmalahti/gulp-tslint#145]
Preparing to deploy application...DONE
Uploading bundle for application: 240522...DONE
Deploying bundle: 1218797 for application: 240522 ...
Waiting for task: 508944657
  building: Processing bundle: 1218797
  building: Parsing manifest
  building: Building image: 1225031
  building: Installing packages
  building: Installing files
  building: Pushing image: 1225031
  deploying: Starting instances
  terminating: Stopping old instances
Application successfully deployed to https://urbanhealthstats.shinyapps.io/UrbanHealthStatisticsPlatform/
Deployment completed: https://urbanhealthstats.shinyapps.io/UrbanHealthStatisticsPlatform/
Warning messages:
1: In value[[3L]](cond) :
  Failed to parse /tmp/RtmpCXpS6k/file5e4264395828/data/dhs_inds.R ; dependencies in this file will not be discovered.
2: In value[[3L]](cond) :
  Failed to parse /tmp/RtmpCXpS6k/file5e4264395828/dhs_inds.R ; dependencies in this file will not be discovered.

**Comment by demurgos** [comment]
How is this related to `gulp-tslint`? Your issue is not clear.

**Comment by panuhorsmalahti** [comment]
Closing for lack of information.
