### ISSUE TITLE
no-var-keyword rule ignored

### ISSUE THREAD

**Issue by pixelshaded** [panuhorsmalahti/gulp-tslint#20]
I have "no-var-keyword": true in my tslint.json. When running my global tslint.cmd, I get linting errors related to this rule. When running gulp tslint, I get no linting errors related to this rule.

My global tslint is 2.3.0-beta. I noticed that gulp-tslint uses tslint 2.2.0-beta. Might this have something to do with it?

**Comment by pixelshaded** [comment]
https://github.com/palantir/tslint/pull/454

Indicates that no-var-keyword was a rule added to 2.3.0.

**Comment by panuhorsmalahti** [comment]
Published gulp-tslint@3.1.0-beta, which uses tslint 2.3.0-beta. This should fix it.

**Comment by pixelshaded** [comment]
3.0.1 fixed it. Thank you.
