### ISSUE TITLE
update tslint to 2.3.1-beta

### ISSUE THREAD

**Issue by thanhc** [panuhorsmalahti/gulp-tslint#22]
Hi,

Would it be possible to update the tslint version to 2.3.1-beta, we're experiencing the same problem as https://github.com/palantir/tslint/issues/456 which has been fixed in 2.3.1.

Thanks

**Comment by panuhorsmalahti** [comment]
Sure, I'm a bit busy at the moment, so a PR is welcome. Basically you just need to test that the new version works with gulp-tslint and there are no breaking changes. I might have the time to do it tomorrow, though.
