### ISSUE TITLE
tslint as a peer dependency

### ISSUE THREAD

**Issue by ashwinr** [panuhorsmalahti/gulp-tslint#26]
TSLint now releases dev versions under the @next tag, which should be installable via gulp-tslint.

**Comment by krtr** [comment]
:+1:

**Comment by panuhorsmalahti** [comment]
Any concrete suggestions? I don't think the dependency should be changed to "tslint@next", right? grunt-tslint is still using a dependency and peerDependency.

**Comment by ashwinr** [comment]
can follow the same convention as https://github.com/palantir/grunt-tslint/blob/master/package.json. grunt-tslint only takes a dependency on tslint (the devDependency is for internal testing only and you don't need that).

**Comment by panuhorsmalahti** [comment]
I released a new version of gulp-tslint with the new tslint option. Check the readme for more information. I think this is sufficient, so the peerDependency change is not required.

**Comment by panuhorsmalahti** [comment]
gulp-tslint 4.x now uses tslint as a peer dependency.
