### ISSUE TITLE
Output to File

### ISSUE THREAD

**Issue by Talento90** [panuhorsmalahti/gulp-tslint#32]
Any way to redirect the output to a file? 

This not work :(

```
gulp.task('tslint', 'Lints all TypeScript source files', function(){
  return gulp.src(tsFiles)
  .pipe(tslint())
  .pipe(tslint.report('verbose'))
  .pipe(gulp.dest('./reports.html'));
});
```

**Comment by bertrandg** [comment]
+1

**Comment by jmcshane** [comment]
+1

**Comment by panuhorsmalahti** [comment]
You can do it like this: https://github.com/panuhorsmalahti/gulp-tslint/blob/master/test/gulpfile.js#L83

Note that you need the latest gulp-tslint for the example to the work. I'm willing to accept PRs to make this easier.

**Comment by bertrandg** [comment]
Cool, thanks for the solution.

**Comment by jon-adams** [comment]
For what it's worth, there is a gulp plugin that can send the tslint output to a checkstyle-formatted file easily consumable by most CI servers: [gulp-tslint-jenkins-reporter](https://www.npmjs.com/package/gulp-tslint-jenkins-reporter)
