### ISSUE TITLE
Allow type inference?

### ISSUE THREAD

**Issue by johanhar** [panuhorsmalahti/gulp-tslint#33]
Stated in the documentation here: http://www.typescriptlang.org/Handbook#type-inference

We should be allowed to do this (e.g. inside a class):
```
isLoading= false
```
But with this linter we get an error, missing typedef, tho the transcompiler will be able to process it..
So we have to do this:
```
isLoading: boolean = false
```

**Comment by rcchen** [comment]
Are you able to share some additional code surrounding this case? I haven't had issues with type inference while using gulp-tslint, eg. `let isLoading = false;` is inferred correctly as a boolean without explicit typing

**Comment by panuhorsmalahti** [comment]
Yeah, a test case would be nice. In addition, this is likely a tslint issue, not gulp-tslint.

**Comment by adidahiya** [comment]
@johanhar that's the intended effect of the `typedef` rule. If you prefer type inference instead, I suggest you turn off that rule. And yes, this is a question about [tslint](https://github.com/palantir/tslint/issues) rather than gulp-tslint, so this issue can be closed.
