### ISSUE TITLE
whitespace rule throws error when there is no visible whitespace missing

### ISSUE THREAD

**Issue by rolandjitsu** [panuhorsmalahti/gulp-tslint#36]
It looks like when I run tslint on [this](https://github.com/rolandjitsu/ng2-lab/blob/master/src/app/components/glyph/glyph.spec.ts) file, with the [whitespace](https://github.com/rolandjitsu/ng2-lab/blob/master/tslint.json#L60) rule in my `tslint.json`, it makes the linting fail even though it looks all good. The error occurs on the [116](https://github.com/rolandjitsu/ng2-lab/blob/master/src/app/components/glyph/glyph.spec.ts#L116)'th line.

Could this be a bug?

**Comment by panuhorsmalahti** [comment]
You need a whitespace before a variable type specification since you have check-type enabled.
```
	constructor(@Query(Glyph) glyphs: QueryList<Glyph>) {
```

**Comment by rolandjitsu** [comment]
@panuhorsmalahti I also get it [here](https://github.com/rolandjitsu/ng2-lab/blob/master/src/common/firebase_array.ts#L212). Do you know why?

**Comment by panuhorsmalahti** [comment]
No, but note that the error message gives you the character index, which will help you debug the problem.
