### ISSUE TITLE
Override tslint.json with configuration.

### ISSUE THREAD

**Issue by skalidindi** [panuhorsmalahti/gulp-tslint#38]
If a tslint file is found, it seems as though the configuration object is ignored. Is there a way to override certain things from the tslint.json file through the configuration object when calling tslint in gulp.

**Comment by panuhorsmalahti** [comment]
rcloader documentation states that the values in the configuration object will override values in the configuration file: "If the user specifies an object, the following keys will be striped from it and the remaining values will override values found in the config files."

The object here is tslintOptions.configuration as specified in the readme.

Are you sure your configuration object is ignored? You can debug this with e.g. adding ```console.log(options.configuration);`` to https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.js#L88

**Comment by skalidindi** [comment]
Sorry, my mistake. Seems to be behaving correctly.
