### ISSUE TITLE
Output file path as link for WebStorm

### ISSUE THREAD

**Issue by dsnoeck** [panuhorsmalahti/gulp-tslint#39]
I'm using WebStorm as editor and its gulp plugin.

I have notice that if you output the file path using console.log() instead of gulp-utils.log(), then the file path will be rendered as link by WebStorm (and maybe some other editor too). Clicking on it will open the file to the exact position of the error, which is quite great.

The different is gulp-utils.log() will prefix the line with the time between [ ]. As the linting works is done under a few millisecondes, I would propose that you skip it. Anyway, gulp display the time for each tasks and its duration.

If you agree I can work on a pull request.

**Comment by panuhorsmalahti** [comment]
I promised in https://github.com/panuhorsmalahti/gulp-tslint/pull/15 I'll make it a configuration option if someone needs that, but please feel free to submit a PR for this.

**Comment by dsnoeck** [comment]
So after playing a bit I realised that the msbuild from #37 is actually doing what I wanted ! Which make me wondering if this report should be named differently ? But I don't have any idea how.
Anyway, thanks for the quick response.
