### ISSUE TITLE
Output path not relative to project root

### ISSUE THREAD

**Issue by dsnoeck** [panuhorsmalahti/gulp-tslint#40]
My project file structure is like that:
```
* src/
  * app/
    * myapp.ts
* gulpfile.js
* package.json
* tsconfig.json
```
My tslint config is like this:
var tslint = require('gulp-tslint');
```
gulp.task('tslint', function(){
      return gulp.src('src/**/*.ts')
        .pipe(tslint())
        .pipe(tslint.report('prose'));
});
```
But the output is not relative the project root (should output path src/app/myapp.ts):
```
[14:27:30] [gulp-tslint] error app/myapp.ts[17, 5]: comment must start with a space
```
Is it a bug or a wrong configuration ?

**Comment by panuhorsmalahti** [comment]
Can you try setting the base directory like here: https://github.com/panuhorsmalahti/gulp-tslint/blob/master/test/gulpfile.js#L48 ?

**Comment by dsnoeck** [comment]
Thanks for the hint. In my case the solution was that:
```
gulp.src('src/**/*.ts', {base: './'})
```
