### ISSUE TITLE
Update to tslint@3.0.0

### ISSUE THREAD

**Issue by zdychacek** [panuhorsmalahti/gulp-tslint#42]
Hi,

pls update to the newest verion of `tslint`.

Maybe, it would be nice, if `tslint` dependency was moved to peerDependencies. This way it works with `tslint-loader`.

Thanks,

O.

**Comment by ColinEberhardt** [comment]
+1 :-)

**Comment by panuhorsmalahti** [comment]
Updated ``tslint`` to 3.0.0. Made tslint a peer dependency. Bumped major version.
