### ISSUE TITLE
gulp-tslint 

### ISSUE THREAD

**Issue by jseanxu** [panuhorsmalahti/gulp-tslint#46]
Since tslint 3.1.1, whenever a linting error occurs, the gulp plugin causes an exception like this:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
 Error: Failed to lint: app/app.ts[13, 5]: unused variable: 'a'.
```

**Comment by panuhorsmalahti** [comment]
Did you return the task to gulp?

For example,
```
gulp.task('invalid-noemit', function(){
    return gulp.src('input.ts')
        .pipe(tslint())
        .pipe(tslint.report('prose', {
          emitError: false
        }));
});
```
See the return statement.

**Comment by jseanxu** [comment]
I tried it with the return statement and it still throws an exception. The return statement is not required in a grunt task, it is common for more complex projects to do more than just call a plugin. Either way, it should never throw an exception.

**Comment by panuhorsmalahti** [comment]
See the discussion in #19: "Well best practice is to do one of three things: return a stream, return a promise, or use the callback. Returning a stream is the only one where gulp will handle errors (using the error event from the stream). The other two require that you listen for errors on your streams and pass the error to your promise rejection method or the task callback."

Can you paste your gulp-tslint usage?

Furthermore, is emitError true or false for you? If there is at least one failure a PluginError is emitted after execution of the reporters.

It's a bit strange that the new tslint has caused your behaviour.

**Comment by jseanxu** [comment]
I return a promise from my task and error it if any of my plugins error.

Consider task composition scenarios. When I run a build task, then the current plugin is fine, it terminates the task as I would want it. When I run the tslint task from a watcher, then I want it to be non-fatal.

**Comment by panuhorsmalahti** [comment]
Did you try with the ``emitError: false`` option for the watch task?

**Comment by jseanxu** [comment]
I think we are veering away from the original issue here :). The plugin throws an exception on a legitimate use, which is usage without returning the stream.

**Comment by panuhorsmalahti** [comment]
Closing due to lack of information..

**Comment by jseanxu** [comment]
Can you justify the lack of information? Calling the plugin without returning the yielding stream, which is a totally legitimate usage, causes an uncaught exception which terminates gulp. Why is my exact use-case important here?

**Comment by realavaloro** [comment]
I am having the same issue 
```
gulp.task('vet', function () {
    //console.log('Analyzing source with TSLint');
    return gulp
            .src(['./app/**/*.ts'])
            .pipe(tslint())
            .pipe(tslint.report('verbose', {
                emitError: false
            }));
});
```

This thread did not help much...

**Comment by realavaloro** [comment]
I had the same error. Found this https://github.com/panuhorsmalahti/gulp-tslint/issues/19 and I confirm my tslint.json, although valid, was UTF-8-BOM and tslint does not seem to like that.
Setting it to UTF-8 solved it.

**Comment by Anjmao** [comment]
Same here. Tried to lint simple file but got
`stream.js:74
      throw er; // Unhandled stream error in pipe.
SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at loadConfigurationFromPath (C:\Projects\accounting-service\Drivr.Accounting.Web\node_modules\tslint\lib\configuration.js:90:31)`

**Comment by panuhorsmalahti** [comment]
That line is simply parsing the tslint.json file with Object.parse, so it seems that the file it is parsing is not a valid JSON file. You might print ``resolvedConfigFilePath`` in the same function to see which tslint.json it is trying to parse. Then copy the contents of the file to e.g. an online JSON validator.

**Comment by mcoxeter** [comment]
Thanks @panuhorsmalahti, my tslint.json file was empty. Working fine now.
