### ISSUE TITLE
specifying rules through options doesn't work with tslint.config present

### ISSUE THREAD

**Issue by yangmillstheory** [panuhorsmalahti/gulp-tslint#49]
If a `tslint.json` file is present, and you specify rules using 

    {configuration: {rules: {...}}

these rules do not overwrite the corresponding rules in the `tslint.json` (try this with `max-line-length`), furthermore, all the rules in `tslint.json` are used.

I think this is caused by spalger/rcloader#10. See also spalger/rcloader#8.

A temporary solution is to have a secondary configuration file (`tslint.spec.json` in my case), and pass it directly as a string.

**Comment by panuhorsmalahti** [comment]
Good catch, lets try to get the fix for rcloader merged in. :+1:

**Comment by yangmillstheory** [comment]
Hi @panuhorsmalahti, spalger/rcloader#10 was closed - I think that will close this issue. It looks like [he bumped the version to 0.2.0](https://github.com/spalger/rcloader/commit/e8590e3b52542c306699fc38b606a06aad5bc1e0), but I'm not sure if he published yet.

**Comment by panuhorsmalahti** [comment]
@yangmillstheory thanks! I released new version of gulp-tslint with the new rcloader.
