### ISSUE TITLE
Does not seem to do anything

### ISSUE THREAD

**Issue by miffels** [panuhorsmalahti/gulp-tslint#5]
Hi,

I just got a fresh copy of ``gulp-tslint`` from npm. Unfortunately, when I pipe my .ts files into it, nothing seems to happen - even running your sample code does nothing:

```
var gulp = require('gulp');
var tslint = require('gulp-tslint');

gulp.task('tslint', function(){
      gulp.src('source.ts')
        .pipe(tslint())
        .pipe(tslint.report('verbose'));
});
```

I would at least expect some error since ``source.ts`` does not exist on my system.

**Comment by khuezy** [comment]
Hi @panuhorsmalahti ,

I'm having the same issue, even with the tslint.json file.

When I downgrade to 2.0.0, it works flawlessly.

**Comment by panuhorsmalahti** [comment]
Hmm, that's odd. Are you using custom rules?

**Comment by panuhorsmalahti** [comment]
Could you try running the tests, do they work for you? What's the minimum setup to reproduce the issue? (E.g. gulpfile.js and file.ts)?

**Comment by khuezy** [comment]
I think it's because I'm using TypeScript 1.5.0-beta.

**Comment by panuhorsmalahti** [comment]
Does it work when using plain tslint directly?

**Comment by peinearydevelopment** [comment]
You state in the docs: "It must be available or supplied directly through the options." How do you supply it directly through the options? This has had me a bit stuck as well.

**Comment by panuhorsmalahti** [comment]
That it explained in the 'tslint.json can be supplied as a parameter by setting the configuration property.' part of the documentation.

**Comment by ericis** [comment]
I can reproduce. The issue appears easily when the code is in a sub-directory.
https://gist.github.com/ericis/35161f8eca326e001c11

*I've also tried adding tslint.json to the "code" subdirectory to no avail.  I also tried reading in the "tslint.json" from gulp using:

    var tsLintConfig = require("./tslint.json");

    ... .pipe(tslint({ configuration: tsLintConfig }))

*I've also tried copying the contents of tslint.json directly into the "configuration" property above.

Nothing I did got tslint to work properly except placing the .ts files in the root.

**Comment by ericis** [comment]
Solved! Windows users need to use the forward-slash in their path and it magically works!

**Comment by FelschR** [comment]
I'm having this issue right now.
Running tslint directly works.

I'm running gulp 3.9.1, gulp-tslint 7.1.0 and tslint 5.0.0.

**Comment by peterzagoranski** [comment]
+1 ... same configuration as FelschR

**Comment by amirburbea** [comment]
+1 - this is annoying.  Should I just have my gulp file shell out to run tslint directly??

**Comment by begincalendar** [comment]
@FelschR @peterzagoranski @amirburbea 
There is a [pull request](https://github.com/panuhorsmalahti/gulp-tslint/pull/113) (that is yet to be merged), which addresses the issue.
