### ISSUE TITLE
cannot install with typescript@next

### ISSUE THREAD

**Issue by rolandjitsu** [panuhorsmalahti/gulp-tslint#54]
If I try to install this package along with `typescript@next` I get a `tslint@3.3.0 requires a peer of typescript@>=1.7.3 but none was installed.`. I really need to use the nightly build of TS, is there any way to make the install work?

I tried using `npm-shrinkwrap.json`:
```js
{
	"name": "name",
	"version": "0.0.0",
	"devDependencies": {
		"gulp-tslint": {
			"version": "4.3.x",
			"from": "gulp-tslint@4.3.x",
			"dependencies": {
				"tslint": {
					"version": "3.3.x",
					"from": "tslint@3.3.x"
				},
				"typescript": {
					"version": "next",
					"from": "typescript@next"
				}
			}
		},
		"tslint": {
			"version": "3.3.x",
			"from": "tslint@3.3.x",
			"dependencies": {
				"typescript": {
					"version": "next",
					"from": "typescript@next"
				}
			}
		}
	}
}
```
But that did not solve my problem.

**Comment by rolandjitsu** [comment]
Also, note that if I do not add `tslint` as dependency in `package.json`, it will not install tslint at all and throw: `npm WARN EPEERINVALID gulp-tslint@4.3.1 requires a peer of tslint@^3 || >=3.1.0-dev || >=3.2.0-dev || >=3.2.1-dev but none was installed.`

**Comment by rolandjitsu** [comment]
tslint seems to have a `@next` branch (as pointed out in [970](https://github.com/palantir/tslint/issues/970)) that points to the `@next` branch of TS. Might be a good idea to adopt the same principle.

**Comment by adidahiya** [comment]
This is an unfortunate consequence of having lots of dev releases. There's no good semver range that captures all the desired versions, and it doesn't seem right to have the maintenance burden of multiple release channels cascade through libraries (typescript@next &rarr; tslint@next &rarr; gulp-tslint@next &rarr; etc.). Maybe gulp-tslint should just depend on a wildcard `*` version of tslint for convenience?

**Comment by rolandjitsu** [comment]
That is true, might make sense to have a wildcard since it actually depends on tslint anyway. Only when there are breaking changes on major version releases might pose some issues.

**Comment by panuhorsmalahti** [comment]
The problem with "*" is that gulp-tslint doesn't work with tslint 2.x anymore I believe due to breaking changes. And when somebody depends on the current gulp-tslint but in the future tslint has a breaking change then this version of gulp-tslint will not work anymore.

 I think the "real fix" would be to improve npm's semantic versioning, e.g. to allow a peer dependency to something like "^3-dev". Having a maintenance burden is not fun, but it's better than breaking stuff.

I released gulp-tslint 4.3.2, which added more compatibility to tslint dev releases. Can you try if it fixes your issue?

**Comment by rolandjitsu** [comment]
That seems to have fixed it. But, when I run the linter, I get:
```shell
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/rolandjitsu/Projects/bolijo/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/rolandjitsu/Projects/bolijo/node_modules/tslint/lib/tslint.js:24:44)
    at /Users/rolandjitsu/Projects/bolijo/node_modules/gulp-tslint/index.js:96:34
    at respond (/Users/rolandjitsu/Projects/bolijo/node_modules/rcloader/index.js:73:7)
    at respond (/Users/rolandjitsu/Projects/bolijo/node_modules/rcfinder/index.js:140:7)
    at /Users/rolandjitsu/Projects/bolijo/node_modules/rcfinder/index.js:124:17
    at /Users/rolandjitsu/Projects/bolijo/node_modules/rcfinder/index.js:77:13
    at doNTCallback0 (node.js:430:9)
    at process._tickDomainCallback (node.js:400:13)
```

**Comment by adidahiya** [comment]
@rolandjitsu that's a new error that tslint throws when it can't find a rule matching each rule name specified in tslint.json. `no-trailing-comma` was removed in v3.0.0 - https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v300-dev1

**Comment by rolandjitsu** [comment]
@adidahiya true, thanks. That was the problem. Works like a charm now.

**Comment by panuhorsmalahti** [comment]
Thanks everyone :+1:

**Comment by rolandjitsu** [comment]
@panuhorsmalahti thanks for the quick fix :+1:

**Comment by JKillian** [comment]
> I think the "real fix" would be to improve npm's semantic versioning, e.g. to allow a peer dependency to something like "^3-dev". Having a maintenance burden is not fun, but it's better than breaking stuff.

Agreed. As a sort of workaround, tslint could forgo patch-level release number bumps and only bump the minor version number. Then it'll be easier for packages like gulp-tslint and grunt-tslint to allow for future versions in their dependency strings. This isn't perfect, but it might be the best solution for now.

**Comment by alexeagle** [comment]
happening again:

```
├─┬ UNMET PEER DEPENDENCY tslint@3.7.0-dev.2
│ └── glob@6.0.4
└── typescript@1.9.0-dev.20160409

npm WARN gulp-tslint@4.3.4 requires a peer of tslint@^3 || >=3.1.0-dev || >=3.2.0-dev || >=3.2.1-dev || >= 3.2.2-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev but none was installed.
alexeagle-macbookpro2:angular alexeagle$ ./tools/npm/reshrinkwrap
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/alexeagle/.nvm/versions/node/v5.5.0/bin/node" "/Users/alexeagle/.nvm/versions/node/v5.5.0/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v5.5.0
npm ERR! npm  v3.6.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: tslint@^3 || >=3.1.0-dev || >=3.2.0-dev || >=3.2.1-dev || >= 3.2.2-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev, required by gulp-tslint@4.3.4
```

**Comment by rolandjitsu** [comment]
@alexeagle I've noticed that it happens again as well, but if I completely remove `node_modules` and run the install, it no longer happens. Might it be an issue with npm?

**Comment by alexeagle** [comment]
https://github.com/panuhorsmalahti/gulp-tslint/pull/62 fixed it for me
