### ISSUE TITLE
rulesDirectory option of tslint.json not handled correctly

### ISSUE THREAD

**Issue by JKillian** [panuhorsmalahti/gulp-tslint#55]
gulp-tslint version: 4.3.3
tslint version: 3.5.0
Operating system: All

If a `tslint.json` file specifies a rulesDirectory property, gulp-tslint needs to resolve those paths relative to the location of the `tslint.json` file and provide those to TSLint via the `rulesDirectory` option [found here](https://github.com/panuhorsmalahti/gulp-tslint/blob/cf21a89ee5ad190c4820d75adeb8aaaaf1c04062/index.ts#L153). TSLint has no way of resolving these paths itself since it has no way of knowing where the `tslint.json` file was located.

This is a subtle bug and I understand that it's not super predictable behavior from TSLint, but I'm now sure what TSLint could do differently. [tslint-loader](https://github.com/wbuchwalter/tslint-loader/issues/16) also has a similar bug.

**Comment by valorkin** [comment]
will be fixed by #63 when merged

**Comment by panuhorsmalahti** [comment]
Hopefully somebody tests that this actually works.

**Comment by valorkin** [comment]
I am actually using it :)
https://github.com/valor-software/ng2-bootstrap see package.json
