### ISSUE TITLE
Feature request: VSO reporter

### ISSUE THREAD

**Issue by cgwrench** [panuhorsmalahti/gulp-tslint#64]
It would be great if a reporter for Visual Studio Online/Team Foundation Server integration could be added to this project. I've had such a formatter added to TSLint itself, see https://github.com/palantir/tslint/commit/cee7e71a018aa483288fcdcda5f071ca59423e45.

In order to make use of this new formatter from gulp-tslint, it appears that this formatter would need to be reimplemented as a new reporter for gulp-tslint. Would you like to see such a reporter added to gulp-tslint? If so, then I can contribute a pull request.

Alternatively, the ideal situation would be that I can make use of this new TSLint formatter directly from gulp-tslint, as suggested in https://github.com/panuhorsmalahti/gulp-tslint/issues/27#issuecomment-206799927. Is there likely to be any work being carried out to re-work gulp-tslint to make use of TSLint formatters directly? If so, then again, I am happy to try and contribute.

**Comment by panuhorsmalahti** [comment]
I agree, using tslint formatters from gulp-tslint would be the recommended way to go. I'll be glad to accept PRs.
