### ISSUE TITLE
linter always uses file.relative 

### ISSUE THREAD

**Issue by nojvek** [panuhorsmalahti/gulp-tslint#67]
using something like this

```
gulp.src("foo/**/*.ts").pipe(tslint({formatter: "full"))
```

Currently gives 

```
 [gulp-tslint] error (semicolon) hello/world.ts[82, 67]: Missing semicolon
```

I would expect the path to be either

``
foo/hello/world.ts
``

or

```
/Users/me/Documents/dev/foo/hello.world.ts
```

The ask is because I'm working on a tslint autofixer that can take the output of tslint or gulp-tslint and auto fix the errors.

Currently the gulp-tslint output is not very machine friendly since the paths it emits is missing info.

**Comment by panuhorsmalahti** [comment]
There was a formatter "full" which gives the full path, but this was removed today. For now, you would need to implement your own formatter to get the full path I think, not sure if tslint natively provides the full path to the file.

**Comment by nojvek** [comment]
Why was the full formatter removed though?

**Comment by panuhorsmalahti** [comment]
Because we removed support for gulp-tslint formatters, and only support tslint formatters.

**Comment by panuhorsmalahti** [comment]
Closing as won't fix.
