### ISSUE TITLE
EPEERINVALID for gulp-tslint >4.3.4

### ISSUE THREAD

**Issue by raDiesle** [panuhorsmalahti/gulp-tslint#72]
running npm install for a version higher than 4.3.4 will throw exception

Operating system: windows with firewall, proxy

e.g.
 "gulp-tslint": "5.0.0",

npm WARN package.json gulp-htmlmin@2.0.0 No README data
npm WARN package.json path@0.11.14 path is also the name of a node core module.
npm WARN package.json url@0.10.3 url is also the name of a node core module.
npm WARN unmet dependency \gulp-open\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\read-pkg-up\node_modules\find-up\node_modules\path-exists requires pinkie-promise@'^1.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm ERR! peerinvalid The package tslint does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-tslint@6.0.2 wants tslint@^3.7.3 || 3.7.0-dev.5 || >=3.8.0-dev || >=3.9.0-dev || >=3.10.0-dev || >=3.11.0-dev || >=3.12.0-dev || >=3.13.0-dev || >=3.14.0-dev || >=3.15.0-dev || >=3.16.0-dev

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\dev\\programs\\nodejs\\node.exe" "C:\\dev\\programs\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\dev\code\github\web3-common-build-setup
npm ERR! node -v v4.1.0
npm ERR! npm -v 1.4.12
npm ERR! code EPEERINVALID
npm ERR!

any clue ?

**Comment by steverob2k** [comment]
Increase the version of tslint in your package.json file

**Comment by panuhorsmalahti** [comment]
Yeah, this can be solved easily by modifying the tslint version you're using.

**Comment by raDiesle** [comment]
Hi, sorry for late reply. There was no tslint version before.
I added tslint explicit to my package.json. It was not there before. This solved it !

It is the first gulp plugin I am using, which does not bundle required dependencies to run.

Thanks for hint.
