### ISSUE TITLE
Intercepting lint errors

### ISSUE THREAD

**Issue by ksnyde** [panuhorsmalahti/gulp-tslint#88]
I like to add audio cues to my errors. Works fine in Mocha but I'd like to have this happen with Lint errors too. I rather naively have the following code:

    gulp.task('static', function () {
      return gulp.src(['**/*.ts', '!**/*.d.ts', '!node_modules/**'])
        .pipe(lint())
        .pipe(lint.report({
          emitError: true
        }))
        .on('end', function(...args) {
          warn(`there were linting errors: ${args}`);
        });
    });

By doing this I do appear to be able to detect linting errors (although actually I think it's just always being called). I get no parameters on the emit and so no way to interact with the lint results.

Is there a good example or docs on how to intercede and take actions based lint outcomes?

**Comment by panuhorsmalahti** [comment]
"Failures generated by TSLint are added to file.tslint.", you could access that.

**Comment by ksnyde** [comment]
I don't see any files of the `*.tslint` variety and I am getting lint errors

**Comment by panuhorsmalahti** [comment]
You can loop through the files with the through2 module (from npm), basically the same way plugins do. Take a look here: https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/dealing-with-streams.md

**Comment by ksnyde** [comment]
thanks @panuhorsmalahti
