### ISSUE TITLE
Update to TSLint 4.0

### ISSUE THREAD

**Issue by dominique-mueller** [panuhorsmalahti/gulp-tslint#90]
TSLint 4.0 got released some hours ago, see https://github.com/palantir/tslint/releases/tag/4.0.0. Yet, the update doesn't work with the latest version of gulp-tslint.

Are there any plans when gulp-tslint will be updated?

**Comment by panuhorsmalahti** [comment]
Working on it.

**Comment by panuhorsmalahti** [comment]
Could someone test tslint-4 branch? Basic support seems to be working. I'll probably release it tomorrow.

**Comment by panuhorsmalahti** [comment]
gulp-tslint 7.0.0 is released, which supports tslint 4.x.

**Comment by dominique-mueller** [comment]
Awesome! Thanks for the very quick update!
