### ISSUE TITLE
how to set program in gulp-tslint [tslint 4.0 dropped createProgram]

### ISSUE THREAD

**Issue by wvanderdeijl** [panuhorsmalahti/gulp-tslint#93]
gulp-tslint version: 7.0.0
tslint version: 4.0.1
Operating system: macOS Siera

According to the gulp-tslint README we need to supply the program option to enable type checked rules. This worked fine in previous versions, but I'm trying to upgrade to gulp-tslint 7.0 with tslint 4.0 and the createProgram method seems gone from tslint

**Comment by panuhorsmalahti** [comment]
You need to use the `.Linter` property:

https://github.com/panuhorsmalahti/gulp-tslint/blob/master/gulpfile.js#L8

I need to update the readme to reflect this, maybe someone could do that in a PR?

**Comment by wvanderdeijl** [comment]
thanks. Works like a charm. See PR #94
