### ISSUE TITLE
gulp-tslint not running and displaying "Requiring external module babel-register" error message

### ISSUE THREAD

**Issue by ifthenelse** [panuhorsmalahti/gulp-tslint#96]
I'm setting up for the first time a Typescript stack (a very simplified version is attached below). As soon as I add *gulp-tslint* among gulp required modules and start ```yarn gulp```, I get the error below on the console. I even tried to downgrade *tslint* or gulp version, without success. It asks for a *babel-register* (older versions of gulp ask for *babel-core/register*) module, which is already a dependency.

**environment**
- node version: v6.9.1
- npm (global) version: 4.0.2
- yarn (global) version: v0.17.6
- eslint (global) version: 3.10.2
- gulp version: 3.9.1 
- gulp-tslint version: 7.0.1
- tslint version: 4.0.2
- Operating system: OS X 10.11.6 (15G1108)

**package.json**
```json
{
  "name": "tslint_test",
  "scripts": {
    "gulp": "gulp",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "angular": "^1.5.8",
    "babel-polyfill": "^6.16.0",
    "flux": "^3.1.0"
  },
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.8",
    "babel-preset-latest": "^6.16.0",
    "babel-register": "^6.18.0",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-eslint": "^3.0.1",
    "gulp-tslint": "^7.0.1",
    "gulp-typescript": "^3.1.3",
    "gulp-util": "^3.0.7",
    "ts-loader": "^1.2.2",
    "tslint": "^4.0.2",
    "tslint-eslint-rules": "^3.0.0",
    "typescript": "^2.0.10",
  },
  "eslintConfig": {
    "extends": "angular",
    "plugins": [
      "import"
    ],
    "env": {
      "browser": true
    }
  },
  "babel": {
    "presets": [
      "es2015"
    ],
    "retainLines": true
  }
}
```

**tsconfig.json**
```json
{
  "rulesDirectory": "node_modules/tslint-eslint-rules/dist/rules",
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**gulpfile.babel.js**
```javascript
/* eslint-disable no-var, import/no-extraneous-dependencies, no-console */
import gulp from "gulp";
import gutil from "gulp-util";
import tslint from "gulp-tslint";

gulp.task("tslint", () =>
    gulp.src("src/ts/main.ts")
        .pipe(tslint({
            configuration: "tsconfig.json",
            formatter: "verbose"
        }))
        .pipe(tslint.report({
            summarizeFailureOutput: true
        }))
    );

gulp.task("default", () =>
    gutil.log("Ciao! 😄")
    );
```

Error console output to the command ```$ yarn gulp```
```zsh
yarn gulp v0.17.6
$ gulp 
[01:22:47] Requiring external module babel-register
module.js:471
    throw err;
    ^

Error: Cannot find module './test/parse'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andreacollet/Projects/shado/test/www/htdocs/node_modules/tslint/lib/test.js:27:13)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/andreacollet/Projects/shado/test/www/htdocs/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
error Command failed with exit code 1.
```

**src/ts/main.ts**
```typescript
class Greeter {
    constructor(public greeting: string) { }
    greet() {
        return this.greeting;
    }
};

const greeter = new Greeter("Hello, world!");

alert(greeter.greet());
```

If the line ```import tslint from "gulp-tslint";``` is commented, the gulpfile runs.

I even tried to rebuild the entire dependency tree from scratch, first cleaning cache, yarn.lock file and the entire node_modules directory. Anyway the behavior remains the same.

Can't really figure out what I am doing wrong, I'm thinking to drop tslint since I can't go on with the project.

**Comment by panuhorsmalahti** [comment]
Try this:
https://github.com/yeoman/generator-webapp/issues/356#issuecomment-219557469

**Comment by ifthenelse** [comment]
I already checked that issue yesterday but none of the advices worked.
Ended up clearing global and local modules, both npm and yarn caches and reinstalling dependencies. This time, keeping the exact same configuration, everything went fine. It was a strange behavior indeed.
Sorry for the bother and thank you @panuhorsmalahti
