### ISSUE TITLE
Support `--fix`

### ISSUE THREAD

**Issue by demurgos** [panuhorsmalahti/gulp-tslint#97]
- `gulp-tslint` version: `7.0.1`
- `tslint version`: `4.0.2`
- Operating system: `Linux`

Hi!
The TSLint command line interface provides a `--fix` option to solve simple issues automatically.

Would it be possible to add a `fix` method to output a fixed version of the files  ?

I imagined something like this:
```typescript
gulp
  .src("src/**/*.ts", {base: "src"})
  .pipe(tslint.fix(/* options */)
  .pipe(gulp.dest("src"));
```

If you like the idea, I could take a look at it.

**Comment by panuhorsmalahti** [comment]
Go ahead! It could be fairly simple:
https://github.com/palantir/tslint/blob/master/src/index.ts#L46
https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.ts#L139

**Comment by RomkeVdMeulen** [comment]
Fairly simple indeed.
